### ISSUE TITLE
Would you like to share the souce codes?

### ISSUE THREAD

**Issue by xuzhang5788** [SirRob1997/Crowded-Valley---Results#3]
Thank you for your great repo. Would you like to share the source codes which generated your benchmark results? Many thanks.

**Comment by fsschneider** [comment]
The main part of the code that generated the results is published open-source as the [DeepOBS benchmark suite](https://github.com/fsschneider/DeepOBS/) and is available here on GitHub as well. This library includes the optimization problems, the models, the data processing, the training loops, etc. Specifically, we used the `1.2.0-beta` version of the code using TensorFlow.

[Our paper](https://arxiv.org/abs/2007.01547) should describe all (training) parameters in detail. Together with the DeepOBS library, this should include everything to reproduce our results or benchmark additional optimizers. Let me know if any information or crucial code is missing.

**Comment by fsschneider** [comment]
I am closing this as stale.

If there is any information or crucial code missing feel free to re-open this issue and we are happy to help
